import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  
  docs: [
    { type: "doc", id: "intro", label: "Introduction" },
    {
      type: "category",
      label: "Backend",
      collapsed: false,
      items: [
        "backend/accessing-admin",
        "backend/user-management",
        "backend/data-models",
        "backend/json-configuration",
        "backend/scenarios",
        "backend/vector-datasets",
        "backend/raster-datasets",
        "backend/reference-datasets",
        "backend/monitoring",
        "backend/api-reference",
      ],
    },
    {
      type: "category",
      label: "Frontend",
      collapsed: false,
      items: [
        "frontend/interface-overview",
        "frontend/model-navigation",
        "frontend/filter-panel",
        "frontend/map-panel",
        "frontend/summary-panel",
        "frontend/downloads",
        "frontend/content-pages",
        "frontend/troubleshooting",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        "deployment/server-requirements",
        "deployment/deployment-overview",
        "deployment/environment-configuration",
        "deployment/post-installation",
        "deployment/update-procedures",
        "deployment/backup-recovery",
        "deployment/troubleshooting",
      ],
    },
    {
      type: "category",
      label: "Appendices",
      items: [
        "appendices/a-json-skeletons",
        "appendices/b-admin-columns",
        "appendices/c-permissions",
        "appendices/d-glossary",
      ],
    },
  ],
};

export default sidebars;
